# Generated by Django 5.0.4 on 2024-04-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('dostep', models.CharField(choices=[('Publiczny', 'Publiczny'), ('Ograniczony', 'Ograniczony')], max_length=20)),
                ('haslo_dostepu', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_uzytkownika', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('haslo', models.CharField(max_length=100)),
                ('rola', models.CharField(choices=[('Uzytkownik', 'Uzytkownik'), ('Moderator', 'Moderator'), ('Administrator', 'Administrator')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElementGraficzny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('opis', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uzytkownik'),
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uzytkownik')),
            ],
        ),
    ]
