# Generated by Django 5.0.4 on 2024-05-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_post_haslo_dostepu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dostep',
            field=models.CharField(choices=[('Publiczny', 'Publiczny'), ('Ograniczony', 'Ograniczony')], default='Publiczny', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='tytul',
            field=models.CharField(max_length=100),
        ),
    ]
