# Generated by Django 5.0.4 on 2024-05-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_post_dostep_alter_post_tytul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tytul',
            field=models.CharField(max_length=200),
        ),
    ]
