# Generated by Django 5.0.4 on 2024-05-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_post_tytul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tresc',
            field=models.TextField(max_length=2000),
        ),
    ]
